name: AchievementAndQuests
main: com.ericlam.mc.achievementquests.AchievementQuests
version: ${project.version}
api-version: "1.15"
depend: [HyperNiteMC-Core, PlaceholderAPI, KotlinExtension]
commands:
  achieve:
    description: achieve command
  quests:
    description: quests command